### ISSUE TITLE
scope parser validation

### ISSUE THREAD

**Issue by jacqueline-chan** [UTMediaCAT/mediacat-frontend#5]
url is alive function is pausing the rest of the script and consequently the whole crawl.
Will need to have a timeout function 
Danhua is investigation

**Comment by kstapelfeldt** [comment]
- scope parser "alive" function is not working, so Danhua replaced with another validation that just checks format. 
- we'll try to fix the function to check headers and improve validation, but if it's too difficult, then we'll stick with the format check.

**Comment by jacqueline-chan** [comment]
- If missing http or https, add it to the url for the scope OR require user to state protocol

**Comment by kstapelfeldt** [comment]
* Checking the header of the response to test whether the link is live (nat provided function)<-- code is pushed

## Todo
* Add error checking to initial validation of the scope to ensure there is http://or https:// <-- reject and return to user a message for any domains that do not specify https or http and ask them to fix it.
* When a URL is not live, write error to an error file, but do not stop.

**Comment by kstapelfeldt** [comment]
This is complete and uploaded to branch. @danhuacai to create pull request.
